// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button.vue')['default']
    Count: typeof import('./src/components/Count.vue')['default']
    ModalButton: typeof import('./src/components/ModalButton.vue')['default']
    NCard: typeof import('naive-ui')['NCard']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NIconWrapper: typeof import('naive-ui')['NIconWrapper']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NModal: typeof import('naive-ui')['NModal']
    NPopover: typeof import('naive-ui')['NPopover']
    NSlider: typeof import('naive-ui')['NSlider']
  }
}

export { }
